spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
security:
  oauth2:
    resource:
      user-info-uri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/user
    client:
      client-id: acme
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev?useSSL=false
    username: root
    password: dbpass
    schema-username: root
    schema-password: dbpass
    data-username: root
    data-password: dbpass
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8181/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    schema-username: root
    schema-password: dbpass
    data-username: root
    data-password: dbpass
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always
security:
  oauth2:
    resource:
      user-info-uri: http://${DOCKER_IP:192.168.99.100}:8181/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
