eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
    metadata-map:
      instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    lease-renewal-interval-in-seconds: 5
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/
