spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /**
      url: ${vcap.services.edge-service.credentials.uri:http://localhost:9999}
    auth-service:
      path: /user/**
      url: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/user
    user-service:
      path: /users/**
security:
  oauth2:
    resource:
      user-info-uri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/user
    client:
      access-token-uri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/oauth/token
      user-authorization-uri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/oauth/authorize
      client-id: acme
      client-secret: acmesecret
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /**
      url: http://localhost:9999
    auth-service:
      path: /user/**
      url: http://localhost:8181/user
    user-service:
      path: /users/**
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8181/user
    client:
      access-token-uri: http://localhost:8181/oauth/token
      user-authorization-uri: http://localhost:8181/oauth/authorize
      client-id: acme
      client-secret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/user
    user-service:
      path: /users/**
security:
  oauth2:
    resource:
      user-info-uri: http://${DOCKER_IP:192.168.99.100}:8181/user
    client:
      access-token-uri: http://${DOCKER_IP:192.168.99.100}:8181/oauth/token
      user-authorization-uri: http://${DOCKER_IP:192.168.99.100}:8181/oauth/authorize
      client-id: acme
      client-secret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
