spring:
  profiles:
    active: development
---
server:
  servlet:
    context-path: /uaa
spring:
  profiles: cloud    
  security:
    user:
      password: password 
---
server:
  port: 8181
  servlet:
    context-path: /uaa   
spring:
  profiles: development
  security:
    user:
      password: password
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev?useSSL=false
    username: root
    password: dbpass
    schema-username: root
    schema-password: dbpass
    data-username: root
    data-password: dbpass
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always 
logging:
  level:
    org.springframework.security: DEBUG 
---
server:
  port: 8181
  servlet:
    context-path: /uaa
spring:
  profiles: docker
  security:
    user:
      password: password
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    schema-username: root
    schema-password: dbpass
    data-username: root
    data-password: dbpass
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always 
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
